import Header from "./components/Header";
import "./globals.css";

export const metadata = {
  title: "Movieflix",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon"  href="/mlogo.png" />
      <body className="relative">
        <Header />
        {children}
      </body>
    </html>
  );
}
